### ISSUE TITLE
「%i」を検索するとエラーが発生する

### ISSUE THREAD

**Issue by takiy33** [clear-code/rurema-search#21]
るりまサーチで「%i」を検索したところ下記のエラーが発生しましたので、報告させて頂きました。
下記がエラー発生時の画面キャプチャです。

---
![a](https://cloud.githubusercontent.com/assets/3800237/8018203/dcd3e3a2-0c49-11e5-917e-e6b333fc14bb.png)

**Comment by kou** [comment]
報告ありがとうございます！
たしかに再現しました。あとで調べて直しておきます。

軽く見た感じだとdocs.ruby-lang.orgへのデプロイの仕方の問題っぽいんですよねぇ。エラー画面でCSSがあたっていないのもおかしいですし。

**Comment by takiy33** [comment]
了解しました。ありがとうございます!!!

**Comment by kou** [comment]
docs.ruby-lang.orgだけでの現象なので、 ruby/rurema-search#3 で対応します。
（こっちは閉じます。）

**Comment by takiy33** [comment]
了解しました!

**Comment by kou** [comment]
再現しなくなったのでどこかで直ったんだと思います！
