### ISSUE TITLE
Please add gpl-3.0.txt to license directory.

### ISSUE THREAD

**Issue by tSU-RooT** [clear-code/rurema-search#23]
Because LGPLv3 is a set of additional permissions on top of the GPLv3.
Please see this http://www.gnu.org/licenses/gpl-howto.html http://www.gnu.org/licenses/gpl-faq.html#v3HowToUpgrade

**Comment by kou** [comment]
Good catch!

**Comment by tSU-RooT** [comment]
Thank you!

I found same miss at other clear-code's repository(```clear-code/cutter```). 
I'll open similar issue.
