### ISSUE TITLE
るりまプロジェクトのリンク先

### ISSUE THREAD

**Issue by kyanagi** [clear-code/rurema-search#25]
https://docs.ruby-lang.org/ja/search/ の一番下にある
「検索対象のドキュメントは るりまプロジェクト の成果物です。」のリンク先は、
現在は https://github.com/rurema/doctree/wiki が適切ではないかと思われます。

**Comment by kou** [comment]
たしかにその通りですね！
更新しました。

docs.ruby-lang.orgの方には時期に反映されると思います。
