### ISSUE TITLE
Reflected Xss

### ISSUE THREAD

**Issue by TheGirdap** [clear-code/rurema-search#27]
Hello,

Reflected Xss found ..

https://docs.ruby-lang.org/ja/search/query:import/query:callback/%22%3E%3C/title%3Ealert(XSS%20A%C3%A7%C4%B1%C4%9F%C4%B1)%3C/script%3E%3E%3Cmarquee%3E%3Ch1%3EXSSa%C3%A7%C4%B1%C4%9F%C4%B1%3C/h1%3E%3C/marquee%3E%3D

result ;

ss:

![ekran_resmi_2018-01-24_01 09 36 1](https://user-images.githubusercontent.com/35760403/35323133-97b52082-00fd-11e8-8566-cbf8e119f5b4.png)

search:

search box > ....import+words+payload => reflected xss

https://twitter.com/hamit_cibo

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.

**Comment by kou** [comment]
We've deployed the fix.

**Comment by TheGirdap** [comment]
gift ?
