### ISSUE TITLE
Array#selectにアクセスすると「404 Not Found」になる

### ISSUE THREAD

**Issue by taki** [clear-code/rurema-search#30]
https://docs.ruby-lang.org/ja/search/version:2.6.0/query:select/ から [Array#select {|item| ... } -> [object] ](https://docs.ruby-lang.org/ja/2.6.0/method/Array/i/filter.html)にアクセスした場合に、以下のページが表示されるようです。

![Screenshot from 2019-10-22 07-08-32](https://user-images.githubusercontent.com/3800237/67246987-04d9c680-f49b-11e9-8fa4-b24592880735.png)

**Comment by kou** [comment]
https://github.com/rurema/doctree/pull/1970 で追加されているはずなのに https://docs.ruby-lang.org/ja/2.6.0/class/Array.html に`Array#filter`がないのがおかしいですね。

rurema.clear-code.com の方にはあるんですけどねぇ。
https://rurema.clear-code.com/2.6.0/method/Array/i/filter.html

**Comment by taki** [comment]
本日アクセスしたらぺーじがあったため、クローズします。
