### ISSUE TITLE
Ruby2.6版のBigDecimal#inspect のドキュメントを参照しようとすると「入力エラー」が発生します

### ISSUE THREAD

**Issue by taki** [clear-code/rurema-search#31]
いつも便利に使わせて頂いています。

https://rurema.clear-code.com/query:bigdecimal/query:inspect/ から BigDecimal#inspect の [Ruby 2.6](https://rurema.clear-code.com/2.6.0/method/BigDecimal/i/inspect.html) へ飛ぼうとすると入力エラーが発生します。

![Screenshot from 2020-03-19 07-52-08](https://user-images.githubusercontent.com/3800237/77014956-c3503780-69b6-11ea-8527-b7133a175393.png)

**Comment by kou** [comment]
これ、BitClustのシンタックスハイライト機能が終端なしの`Range`に対応していなくてエラーになるからなんですよ。

https://github.com/rurema/doctree/commit/55e28e00f30092aab254b25592e8f48406734957#diff-3b8de3267235fda393d0c1ea268bf05aR45 で追加されたサンプルコードでエラーが発生します。

```text
終端を持たない範囲オブジェクト:3:6 syntax error, unexpected ')' (BitClust::SyntaxHighlighter::ParseError)
```

後でBitClustを直そうと思って全然手を付けられていないのでBitClustの方に報告しておいてもらえますか？

**Comment by taki** [comment]
報告しました。

**Comment by kou** [comment]
rurema/bitclust#109 がマージされたので見れるようになりました。

**Comment by taki** [comment]
見れました。ありがとうございました。
