### ISSUE TITLE
rdoc link seems broken

### ISSUE THREAD

**Issue by tikkss** [clear-code/rurema-search#39]
Looks like the following `[rdoc]` link in https://rurema.clear-code.com/3.3.0/method/Hash/i/shift.html seems broken.
When I click on it, it returns a 404 Not Found response.

![image](https://github.com/clear-code/rurema-search/assets/4122070/e5017e69-8ccb-496e-a51d-c2772740aba9)

Steps to reproduce
---

1. Visit https://rurema.clear-code.com
1. Input `shift` into the search box
1. Click the `検索` button
1. Click the link for Hash#shift under the 3.3.0 version
    * Then open https://rurema.clear-code.com/3.3.0/method/Hash/i/shift.html
1. Click the [rdoc] link

Expected result
---

Open https://docs.ruby-lang.org/en/3.3/Hash.html#method-i-shift

Actual result
---

Open https://docs.ruby-lang.org/en/3.3.0/Hash.html#method-i-shift
It's 404 Not Found.

Note
---

This issue occurs in versions 3.0.0 and later, and does not occur in versions 2.7.0 and earlier.

- Not Expected result
    - https://rurema.clear-code.com/3.3.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/3.2.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/3.1.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/3.0.0/method/Hash/i/shift.html
- Expected result
    - https://rurema.clear-code.com/2.7.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.6.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.5.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.4.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.3.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.2.0/method/Hash/i/shift.html
    - https://rurema.clear-code.com/2.1.0/method/Hash/i/shift.html

**Comment by kou** [comment]
Good catch!
We should have used `#{MAJOR}.#{MINOR}` instead of `#{MAJOR}.#{MINOR}.0` for Ruby 3.0.0 or later.

**Comment by tikkss** [comment]
Thanks for your quick fix.
It has become very useful 👍
