### ISSUE TITLE
`Etc.#nprocessors` was introduced in Ruby 2.2.0 or later

### ISSUE THREAD

**Issue by tikkss** [clear-code/rurema-search#40]
`Etc.#nprocessors` was introduced in Ruby 2.2.0 or later, but it exists in [the documentation for  Ruby 2.1](https://rurema.clear-code.com/2.1.0/method/Etc/m/nprocessors.html).

See also:

- [Stdlib updates - NEWS-2.2.0 - Documentation for Ruby 3.4](https://docs.ruby-lang.org/en/master/NEWS/NEWS-2_2_0.html#label-Stdlib+updates+-28outstanding+ones+only-29)

Steps to reproduce
---

1. Visit https://rurema.clear-code.com
1. Input `nprocessors` into the search box
1. Click the `検索` button

Expected result
---

Show `Etc.#nprocessors` in 2.2.0 or later

Actual result
---

Show `Etc.#nprocessors` in 2.1.0 or later

**Comment by kou** [comment]
We need to update https://github.com/rurema/doctree/blob/master/refm/api/src/etc.rd something like:

```diff
diff --git a/refm/api/src/etc.rd b/refm/api/src/etc.rd
index b29216836..984f371cc 100644
--- a/refm/api/src/etc.rd
+++ b/refm/api/src/etc.rd
@@ -240,6 +240,7 @@ Etc.confstr(Etc::CS_GNU_LIBC_VERSION) # => "glibc 2.18"
 Etc.confstr(Etc::CS_GNU_LIBPTHREAD_VERSION) # => "NPTL 2.18"
 #@end
 
+#@since 2.2
 --- nprocessors -> Integer
 
 有効な CPU コア数を返します。
@@ -248,6 +249,7 @@ Etc.confstr(Etc::CS_GNU_LIBPTHREAD_VERSION) # => "NPTL 2.18"
 require 'etc'
 p Etc.nprocessors #=> 4
 #@end
+#@end
 
 == Constants
 
```

But Ruby 2.1 is EOL. So it will not be accepted...

**Comment by tikkss** [comment]
I think it is a reasonable decision not to maintain the documentation for EOL Ruby versions.

Thanks for your suggestion!
